version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: did-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/did-service
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - did-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=did-service
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - did-network

volumes:
  mongodb_data:
    name: did-service-mongodb-data

networks:
  did-network:
    name: did-service-network
    driver: bridge